version: '3'
services:
  wrapper:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CRED=pro
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
