version: '3'
services:
  wrapper:
    image: mobarrio/cloudwatch_wrapper:latest
    container_name: cloudwatch_wrapper
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CRED=pre
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ./env.js:/usr/src/app/env.js
